name: talky

packages:
  - app/**
  - features/**
  - libraries/**

command:
  bootstrap:
    environment:
      sdk: ">=3.5.0 <4.0.0"
    dev_dependencies:
      build_runner: ^2.4.12
      mocktail: ^1.0.4
      very_good_analysis: ^6.0.0
