name: core
description: Talky - Core Library
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^8.0.0
  go_router: ^14.2.8
  meta: ^1.15.0
  result_dart: ^1.1.1
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - .env
    - .env.dev
