name: core
description: Talky - Core Library
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  go_router: ^14.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
