name: talky_app
description: Chat application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auth:
    path: ../../features/auth
  core:
    path: ../../libraries/core
  flutter:
    sdk: flutter
  i18n:
    path: ../../libraries/i18n
  talky_ui_kit:
    path: ../../libraries/talky_ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
