arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/l10n/gen
output-class: AuthLocalizations
output-localization-file: auth_localizations.dart
synthetic-package: false
nullable-getter: false