name: auth
description: Talky Application - Auth Module
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  core:
    path: ../../libraries/core
  flutter:
    sdk: flutter
  i18n:
    path: ../../libraries/i18n
  talky_ui_kit:
    path: ../../libraries/talky_ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
